### ISSUE TITLE
Error when running test

### ISSUE THREAD

**Issue by leminhkieu** [RexValkering/socialforcemodel#2]
Dear Rex,

I tried to run test.py and a problem showed up: 

usage: ipykernel_launcher.py [-h] [-s STEPS] [-o OUTFILE] [-r REPETITIONS]
                             corridor.yaml
ipykernel_launcher.py: error: unrecognized arguments: -f
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

I think this has to do with the argparse method. Have you seen this issue before and how to solve it?

Thanks

**Comment by RexValkering** [comment]
Hi Minh,

You seem to call your file using a -f parameter, but -f is not defined in
your argparse implementation. What is your exact function call?

The following code (I'm assuming you're using the test.py method) shows
four possible parameters: a YAML configuration file, the number of steps
(-s), a file to save measurements (-o) and the number of repetitions (-r).

 import argparse
 import sys
 parser = argparse.ArgumentParser()
 parser.add_argument('file', help='YAML-file')
 parser.add_argument('-s', '--steps', help='Number of steps', type=int,
default=500)
 parser.add_argument('-o', '--outfile', help='File for measurements',
default='measurements')
 parser.add_argument('-r', '--repetitions', default=1, type=int)
 args = parser.parse_args(sys.argv[1:])
 main(args)

I have actually been using a more advanced version of 'main.py' (or
'test.py') to run the simulation. I'll see if I can commit it to github, it
might be useful.

Rex

**Comment by leminhkieu** [comment]
Hi Rex,

Thanks for the quick reply. I used your test.py. 
I am not quite familiar with the args parser. Would you be able to commit a new main.py ? I am happy to test and give you feedback. 

Thank you
Minh

**Comment by RexValkering** [comment]
There's a new file called `tests/advanced.py` which contains the code I've used for running the program and storing simulation data. Example

```bash
cd tests
python advanced.py corridor.yaml -m 10 -i 5 -F
```

The parameters mean:

- `corridor.yaml`: use the corridor.yaml config file
- `-m 10`: spawn ten pedestrians
- `-i 5`: create an image every 5 steps
- `-F`: replace old measurement files if they exist
